set(CMAKE_SYSTEM_VERSION "10.0.19041.0" CACHE STRING "Pinned Windows SDK version" FORCE)

set(CMAKE_POLICY_DEFAULT_CMP0091 NEW)
set(
    CMAKE_MSVC_RUNTIME_LIBRARY
    "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL"
    CACHE STRING "Pinned dynamic MSVC runtime for Legacy packaging" FORCE
)
set(
    XXSNAP_WINDOWS7_SUBSYSTEM_VERSION
    "6.01"
    CACHE STRING "Minimum Windows subsystem version for Legacy executables" FORCE
)

set(CMAKE_C_FLAGS_INIT "${CMAKE_C_FLAGS_INIT} /D_WIN32_WINNT=0x0601 /DWINVER=0x0601 /DNTDDI_VERSION=0x06010100")
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_CXX_FLAGS_INIT} /D_WIN32_WINNT=0x0601 /DWINVER=0x0601 /DNTDDI_VERSION=0x06010100")
